/**
 * this file was auto-generated by AliceLex
 * https://github.com/YuhangGe/alicelex
 */
(function(D, $) {
    var DEFAULT = 34, WEI = 35, CSS = 36, VALUE = 41, URL = 42;
    var lexer_css = function() {
        this.base();
        this.START_ACTION = 34;
        this.TABLE = {
            _base : (window.Int32Array?new Int32Array(43):new Array(43)),
            _default : (window.Int32Array?new Int32Array(43):new Array(43)),
            _check : (window.Int32Array?new Int32Array(439):new Array(439)),
            _next : (window.Int32Array?new Int32Array(439):new Array(439)),
            _action : (window.Int32Array?new Int32Array(43):new Array(43)),
            _eqc : (window.Int32Array?new Int32Array(256):new Array(256))
        };

        D._str_to_arr(["\0\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\2\3\1\20\47\76\x55\15\20\x6c\x83\12\x9a\xb3\xd0\xed\1\1\u010a\u0127\u0144\u0161\u017e\1\1\u019b\1", "\1\20\0\2\17\3\0\2\22\5\0\3\24\3\0\2\26\2\31\4\0\2\37\2\40\6\0\2\46\2\47\2\0\2\36", "\1\2\53\13\0\2\22\3\0\2\17\2\21\2\22\2\21\11\24\2\30\2\22\2\24\2\31\2\24\2\34\4\0\3\24\3\0\3\24\11\25\4\0\3\25\5\0\3\25\3\0\3\25\11\26\4\0\3\26\5\0\3\26\3\0\3\26\11\27\4\0\3\27\5\0\3\27\3\0\3\27\11\32\3\0\4\32\5\0\3\32\3\0\3\32\11\33\3\0\4\33\5\0\3\33\3\0\3\33\11\35\3\0\2\35\2\0\3\35\4\0\3\35\3\0\3\35\35\36\36\37\36\40\36\43\36\44\36\45\36\46\36\47\36\52","\1\2\16\13\0\2\22\3\0\2\17\2\21\2\22\2\20\12\30\2\22\2\30\2\35\2\30\2\12\4\0\3\30\3\0\3\30\5\26\2\27\4\26\4\0\3\26\5\0\3\26\3\0\13\26\4\0\3\26\5\0\3\26\3\0\13\26\4\0\3\26\5\0\2\26\2\34\3\0\3\26\11\32\3\0\4\32\5\0\3\32\3\0\3\32\11\33\3\0\4\33\5\0\3\33\3\0\3\33\11\30\3\0\2\30\2\0\2\30\2\20\4\0\3\30\3\0\3\30\35\36\15\41\2\1\21\41\14\42\2\1\22\42\4\4\11\30\2\40\2\37\2\30\2\21\2\31\3\24\2\3\2\2\3\30\3\4\3\30\4\4\3\6\2\5\11\32\3\6\2\32\2\6\2\32\5\6\3\32\3\6\3\32\2\5\3\6\4\11\11\33\3\11\2\33\2\11\2\33\3\11\2\10\2\11\3\33\3\11\3\33\3\11\2\7\15\50\2\13\21\50\14\51\2\13\22\51\4\15\11\26\2\47\2\46\2\15\3\26\2\15\2\23\3\15\2\25\2\26\3\15\3\26\3\14\2\15", "\0\1\7\4\26\22\6\21\11\23\15\12\20\24\17\2\0\2\14\24\26\13\13\13\3\3\5\10\13\2\16\26\26\0\0\0\0\0\24\24\0\0\0\16", "\1\12\30\2\3\2\33\3\3\24\30\2\3\2\2\2\14\2\22\4\30\2\15\2\27\2\1\4\30\2\20\2\21\2\30\13\17\2\23\2\34\6\30\7\32\25\31\5\30\2\31\2\30\2\12\6\32\3\31\2\4\2\16\2\31\2\26\2\5\2\13\2\7\2\6\2\31\2\10\2\31\2\11\2\25\6\31\2\24\2\30\2\35\x83\30"], [this.TABLE._base, this.TABLE._default, this.TABLE._check, this.TABLE._next, this.TABLE._action, this.TABLE._eqc]);
    };
    lexer_css.prototype = {
        read_ch : function() {
            if(this.idx >= this.end)
                return this.chr = -1;
            else {
                this.chr = this.src.charCodeAt(this.idx++);

                if(this.chr >= 65 && this.chr <= 90)
                    this.chr += 32;

                return this.chr;
            }
        },
        action : function(action) {
            switch(action) {
                case 0:
                    this.yystyle="string";
                    break;
                case 6:
                    this.yygoto(CSS);
                    break;
                case 3:
                    this.yygoto(WEI);
                    break;
                case 1:
                    this.yystyle="number"
                    break;
                case 2:

                    break;
                case 21:

                    break;
                case 4:
                    this.yystyle="wei";
                    break;
                case 17:

                    break;
                case 5:
                    this.yygoto(DEFAULT);
                    break;
                case 16:
                    this.yygoto(DEFAULT);
                    break;
                case 8:
                    this.yygoto(VALUE);
                    break;
                case 7:
                    this.yystyle="keyword";
                    break;
                case 18:

                    break;
                case 12:
                    this.yystyle="wei"; this.yygoto(URL);
                    break;
                case 11:
                    this.yystyle="number";
                    break;
                case 9:
                    this.yystyle = "string";
                    break;
                case 15:
                    this.yygoto(CSS);
                    break;
                case 10:
                    this.yystyle="value";
                    break;
                case 19:
                    break;
                case 14:
                    this.yygoto(VALUE);this.yystyle="wei";
                    break;
                case 13:
                    this.yystyle="string";
                    break;

                default :
                    break;
            }
        }
    };
    $.inherit(lexer_css, D._LexerBase);

    D.register({
        name : 'css',
        instance : new lexer_css()
    });
})(dLighter._Lexer, dLighter.$);
